### ISSUE TITLE
Caveat

### ISSUE THREAD

**Issue by josephgupkim** [Sypoo/bwa-u4-feature-request#3]
I'm glad you didn't skimp out on the Caveat section as some feature requests have unfortunately done.

The only "issue" I could state here is that I wish you had thought of possible problems that were "outside of the box".

Does the Search functionality work if the user were to press "enter" anytime on the page; or only when in the input?
If the user presses enter with no input (empty string) will the search function still trigger?
If so, will it show all the results, none of the results, something else?

Although it wasn't mandatory for you to solve solutions like this, I'm curious on how you would have planned for these "problems".

**Comment by Sypoo** [comment]
I fully understand what you are saying. I will work on my "out of the box" thinking :)
